version: '3'

networks: 
    rat-api:

volumes:
    mysqldata:

services: 
    mysql:
        image: mysql
        tty: true
        restart: always
        ports:
            - 3306:3306
        environment: 
            MYSQL_DATABASE: rat-API
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_USER: etna
            MYSQL_PASSWORD: etna_password
        networks: 
            - rat-api
        volumes: 
            - mysqldata:/var/lib/mysql
            - ./database:/docker-entrypoint-initdb.d
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql
        depends_on: 
            - mysql
        ports: 
            - 80
        environment: 
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        networks: 
            - rat-api
        restart: always
    
    api:
        build: .
        links:
            - mysql
        depends_on: 
            - mysql
        ports:
            - 5000:5000
        networks: 
            - rat-api
        restart: always
        command: bash -c "sleep 20 && php artisan migrate && php artisan passport:install && php artisan serve --host=0.0.0.0 --port=5000"
    
    notification:
        build: ./notification
        ports:
            - 3000:3000
        networks: 
            - rat-api
        restart: always
        command: npm run start
        