CREATE TABLE USER(
    id INT AUTO_INCREMENT NOT NULL,
    email VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    pseudo VARCHAR(255) DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB CREATE TABLE FILE(
    id INT AUTO_INCREMENT NOT NULL,
    user_id INT DEFAULT NULL,
    NAME VARCHAR(255) NOT NULL,
    path VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    private TINYINT(1) NOT NULL,
    INDEX IDX_8C9F3610A76ED395(user_id),
    PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB CREATE TABLE token(
    id INT AUTO_INCREMENT NOT NULL,
    user_id INT NOT NULL,
    created_at DATETIME NOT NULL,
    token VARCHAR(255) NOT NULL,
    INDEX IDX_5F37A13BA76ED395(user_id),
    PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ALTER TABLE FILE ADD CONSTRAINT
    FK_8C9F3610A76ED395 FOREIGN KEY(user_id) REFERENCES USER(id)
ALTER TABLE
    token ADD CONSTRAINT FK_5F37A13BA76ED395 FOREIGN KEY(user_id) REFERENCES USER(id)